version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tinyinsta
      POSTGRES_USER: tinyinsta
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tinyinsta
      SPRING_DATASOURCE_USERNAME: tinyinsta
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_UPLOAD_DIR: /tmp
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /tmp:/tmp

volumes:
  pgdata: